name=input("name:")
age=int(input("age:"))
course=input("course:")
college=input("college:")
address = input("Enter address: ")
print("\n----- STUDENT ID CARD -----")
print("Name:", name)
print("Age:", age)
print("Course:", course)
print("College:", college)
print("Address:", address)         